Controllers/ilanController.cs
using stajdeneme.Models;
using System.Linq;
using System.Web.Mvc;
using System.Data;
using System.Web.UI.WebControls;
using System.Net;
using System.Collections.Generic;
using System;

namespace stajdeneme.Controllers
{
    public class ilanController : Controller
    {
        stajdenemeEntities3 db = new stajdenemeEntities3();
        // GET: Kategori
        [_SessionControl]
        public ActionResult Index()
        {
            var aranacak = from d in db.tbl_ilan select d;
            return View(aranacak.ToList());
         
        }
        public ActionResult ilan()
        {

            var aranacak = from d in db.tbl_ilan select d;
            return View(aranacak.ToList());
        }

        [_SessionControl]
        [HttpGet]
        public ActionResult ilanEkle()
        {
            List<SelectListItem> ilan = (from u in db.tbl_tip.ToList()
                                         select new SelectListItem
                                         {
                                             Text = u.tip_name,
                                             Value = u.tip_id.ToString()


                                         }).ToList();
            ViewBag.v = ilan;

            return View();
        }
        [HttpPost]
        public ActionResult ilanEkle(tbl_ilan p)
        {
            if (!ModelState.IsValid) { return View("ilanEkle"); }
            List<SelectListItem> ilan = (from u in db.tbl_tip.ToList()
                                         select new SelectListItem
                                         {
                                             Text = u.tip_name,
                                             Value = u.tip_id.ToString()


                                         }).ToList();
            ViewBag.v = ilan;

            var bol = db.tbl_tip.Where(m => m.tip_id == p.tbl_tip.tip_id).FirstOrDefault();

            p.tbl_tip = bol;
            p.ilan_tarih = DateTime.Now;
            db.tbl_ilan.Add(p);
            db.SaveChanges();
            return RedirectToAction("index");
        }
        
        [HttpPost]
        public ActionResult RGuncelle(tbl_ilan id)
        {
            var getir = db.tbl_ilan.Find(id.ilan_id);

            getir.ilan_aciklama = id.ilan_aciklama;
            getir.ilan_baslik = id.ilan_baslik;
            getir.ilan_tarih = id.ilan_tarih;
            getir.ilan_beceriler = id.ilan_beceriler;
           
            getir.ilan_durum = id.ilan_durum;

            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [_SessionControl]
        [HttpGet]
        public ActionResult Guncelle(int id)
        {
            var getir = db.tbl_ilan.Find(id);
            //List<SelectListItem> ilan = (from u in db.tbl_tip.ToList()
            //                             select new SelectListItem
            //                             {
            //                                 Text = u.tip_name,
            //                                 Value = u.tip_id.ToString()


            //                             }).ToList();
            //ViewBag.v = ilan;
            return View("Guncelle",getir);
        }
        
        public ActionResult Sil(int id)
        {
            var kategori = db.tbl_ilan.Find(id);
            db.tbl_ilan.Remove(kategori);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

Views/ilan/Guncelle.cshtml
@model stajdeneme.Models.tbl_ilan
@{
    ViewBag.Title = "KategoriGuncelle";
    Layout = "~/Views/Shared/_ViewLayout.cshtml";
}
<title>Yeşil-Mavi Yazılım</title>
@using (Html.BeginForm("RGuncelle", "ilan", FormMethod.Post))
{
    <div style="margin-top:10px">

        @Html.HiddenFor(x => x.ilan_id)
        @*@Html.TextBoxFor(m => m.ilan_sahibi, new { @class = "form-control" })*@
    </div>
    <div style="margin-top:10px">
        @Html.Label("İlan Sahibi")

        @Html.TextBoxFor(m => m.ilan_sahibi, new { @class = "form-control" })
    </div>
    <div style="margin-top:10px">
        @Html.Label("İlan Başlık")

        @Html.TextBoxFor(m => m.ilan_baslik, new { @class = "form-control" })
    </div>
    <div style="margin-top:10px">
        @Html.Label("İlan Açıklama")

        @Html.TextBoxFor(m => m.ilan_aciklama, new { @class = "form-control" })
    </div>
    <div style="margin-top:10px">
        @Html.Label("İlan Beceriler")

        @Html.TextAreaFor(m => m.ilan_beceriler, new { @class = "form-control" })
    </div>
    <div style="margin-top:10px">
        @Html.Label("İlan Tarih")

        @Html.TextBoxFor(m => m.ilan_tarih, new { @class = "form-control datetime", @placeholder = "Gün/Ay/Yıl", @id = "datetime", @autocomplete = "off" })
        @Html.ValidationMessageFor(m => m.ilan_tarih, "", new { @style = "color:red" })
    </div>

    <div style="margin-top:10px">


        <div class="form-group col-md-12">
            <label>  @Html.Label("İlan Durum")</label><br />

            <label class="radio-inline">
                @Html.RadioButtonFor(m => m.ilan_durum, false)False
            </label>
            <label class="radio-inline">
                @Html.RadioButtonFor(m => m.ilan_durum, true) True
            </label>
            <br />

        </div>
        @*@Html.ValidationMessageFor(m => m.ilan_tip, "", new { @style = "color:red" })*@
    </div>
    <div style="margin-top:10px">
        <button class="btn btn-success">Güncelle</button>
        <button data-target="~/ilan/Index" class="btn btn-danger">Geri</button>
    </div>

}

Views/ilan/Index.cshtml
@using stajdeneme.Models
@model List<tbl_ilan>
@{
    ViewBag.Title = "index";
    Layout = "~/Views/Shared/_ViewLayout.cshtml";
}


<title>Yeşil-Mavi Yazılım </title>
<style>
    .mfp-close {
        cursor: pointer !important;
    }

    body {
        background: #f1f1f1;
    }

    table {
        background: #fff;
    }

    th, td {
        padding: 15px;
        text-align: left;
    }

    tr:hover {
        background-color: #f5f5f5;
    }

    .styled-table {
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        font-family: sans-serif;
        min-width: 400px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }

        .styled-table thead tr {
            background-color: #009879;
            color: #ffffff;
            text-align: left;
        }

        .styled-table th,
        .styled-table td {
            padding: 12px 15px;
        }

        .styled-table tbody tr {
            border-bottom: 1px solid #dddddd;
        }

            .styled-table tbody tr:nth-of-type(even) {
                background-color: #f3f3f3;
            }

            .styled-table tbody tr:last-of-type {
                border-bottom: 2px solid #009879;
            }
</style>
<table class="table table-bordered">
    <tr>
        <th>  id</th>
        <th>  Sahibi</th>
        <th>  Başlık</th>
        <th>  Açıklama</th>
        <th>  Beceriler</th>
        <th>  Tarih</th>
        <th>  Tip</th>
        <th>  Durum</th>

        <th> Sil</th>
        <th> Güncelle</th>
    </tr>
    <tbody>
        @foreach (var ktgr in Model)
        {
            <tr>
                <th>@ktgr.ilan_id</th>
                <td>@ktgr.ilan_sahibi</td>
                <td>@ktgr.ilan_baslik</td>
                <td>@ktgr.ilan_aciklama</td>
                <td>@ktgr.ilan_beceriler</td>
                <td> @Convert.ToDateTime(ktgr.ilan_tarih).ToString("dd/MM/yyyy")</td>
                <td>@ktgr.ilan_tip</td>
                <td>@ktgr.ilan_durum</td>
                <td><a href="~/ilan/Sil/@ktgr.ilan_id" class="btn btn-danger">Sil</a></td>

                <td><a href="~/ilan/Guncelle/@ktgr.ilan_id" class="btn btn-success">Güncelle</a></td>
            </tr>

        }
    </tbody>
</table>
@*@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))*@
<a href="/ilan/ilanEkle" class="btn btn-success">Yeni İlan Ekle</a>
<a href="~/Basvuru/index" class="btn btn-success">Geri dön</a>

Views/ilan/ilan.cshtml
@using stajdeneme.Models
@model List<tbl_ilan>
@{
    ViewBag.Title = "ilan";
    Layout = "~/Views/Shared/_ViewLayout.cshtml";
}


<title>Yeşil-Mavi Yazılım İlanlar</title>


@foreach (var s in Model)
{
    if (@s.ilan_durum==true)
    {

    
    <div class="form-row">

        <div class="form-group col-md-12">
           
                <div class="card ">
                    @*<img class="card-img-top img-fluid" src="" width="200px" height="200px">*@
                    <div class="card-img-overlay card-body">
                        <h3 class="h3 u-clear-gap-bottom u-text-ilan-baslik" style="color: #217fe7;" >@s.ilan_baslik</h3>
                        <p class="card-text text-danger">
                            @*@s.ilan_id*@
                            <h5 class="  h5 u-text-ilan-altbaslik" style="color: #25e359;"> @s.ilan_aciklama </h5><br>

                            @s.ilan_beceriler<br />
                                             <h5 class="u-font-size-sm u-gap-right-medium u-text-nowrap"><i class="glyphicon glyphicon-calendar"> </i>
                                                 @Convert.ToDateTime(s.ilan_tarih).ToString("dd/MM/yyyy")
                                                                     </h5>  </p>

                                <a href="~/Basvuru/Insert?basvuru_ilanid=@s.ilan_id&tip=@s.ilan_tip" class="btn btn-danger" value="@s.ilan_id">Başvur<i class="glyphicon glyphicon-menu-right"> </i><i class="glyphicon glyphicon-menu-right"> </i></a>
                         

                    </div>
                </div>
            </div>

     
    </div>
    }
}


@*<div class="container mt-3">

    <div class="row">
        <div class="col-sm-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Special title treatment</h5>
                    <p class="card-text">With supporting text below as a natural lead-in</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>

    </div>
</div>*@



Views/ilan/ilanEkle.cshtml

@model stajdeneme.Models.tbl_ilan
@{
    ViewBag.Title = "ilanEkle";
    Layout = "~/Views/Shared/_ViewLayout.cshtml";
}
<title>Yeşil-Mavi Yazılım</title>
@using (Html.BeginForm("ilanEkle", "ilan", FormMethod.Post))
{

    <div style="margin-top:10px">
        <label>İlan Sahibi</label>
        @Html.TextBoxFor(m => m.ilan_sahibi, new { @class = "form-control", @Value = "admin" })
        @Html.ValidationMessageFor(m => m.ilan_sahibi, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:10px">
        <label>İlan Başlığı</label>
        @Html.TextBoxFor(m => m.ilan_baslik, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.ilan_baslik, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:10px">
        <label>İlan açıklaması</label>
        @Html.TextBoxFor(m => m.ilan_aciklama, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.ilan_aciklama, "", new { @style = "color:red" })
    </div>

    <div style="margin-top:10px">
        <label>İlan Becerileri</label>
        @Html.TextAreaFor(m => m.ilan_beceriler, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.ilan_beceriler, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:10px">
        <label>İlan Tip</label>
        @Html.DropDownListFor(m => m.tbl_tip.tip_id, (List<SelectListItem>)ViewBag.v, "Seçim yapınız..", new { @class = "form-control" })
        @*@Html.DropDownListFor(m => m.tbl_universite.universite_id, (List<SelectListItem>)ViewBag.uni, new { @class = "form-control", @name = "Universiteler", @id = "Universite" })*@

        @Html.ValidationMessageFor(m => m.ilan_tip, "", new { @style = "color:red" })
    </div>
    <div style="margin-top:10px">
        <label>İlan Durum</label><br />

        <label class="radio-inline">
            @Html.RadioButtonFor(m => m.ilan_durum, false)False
        </label>
        <label class="radio-inline">
            @Html.RadioButtonFor(m => m.ilan_durum, true, new { Checked = "checked" }) True
        </label>
        <br />

    </div>
    <div style="margin-top:10px">
        <button class="btn btn-success" id="button1">Yeni İlan Ekle</button>
        <a href="~/ilan/index" class="btn btn-success">Geri dön</a>
    </div>
    <script>
        $('#button1').click(function () { alert("Ekleme işleminiz yapıldı"); });
    </script>
}
