Controllers/BasvuruController.cs

using Newtonsoft.Json;
using PagedList;
using stajdeneme.Controllers;
using stajdeneme.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;


namespace basvurudeneme.Controllers
{

    public class BasvuruController : Controller
    {

        // GET: Basvuru
        stajdenemeEntities3 db = new stajdenemeEntities3();


        //public ActionResult Index(int sayfa = 1)
        //{
        //    var degerler = db.tbl_basvuru.ToList().ToPagedList(sayfa, 2);
        //    return View(degerler);
        //}
        [_SessionControl]
        public ActionResult Index(string ara, int sayfa = 1)
        {



            var aranacak = from d in db.tbl_basvuru select d;
            var aranacak1 = from d in db.tbl_basvuru select d;


            if (!string.IsNullOrEmpty(ara))
            {

                aranacak = aranacak.Where(m => m.basvuru_ad.Contains(ara) || m.basvuru_soyad.Contains(ara));

            }
            
            

            return View(aranacak.ToList().ToPagedList(sayfa, 50));
        }

        [HttpGet]
        public ActionResult Insert(string basvuru_ilanid, int tip = 0) { 
            
            List<SelectListItem> bos = new List<SelectListItem>();
            if (basvuru_ilanid == null || tip == 0)
            {
                return RedirectToAction("ilan", "ilan");

            }
                            
            ViewBag.bolum = bos;
            ViewBag.il = bos;
            ViewBag.ilce = bos;
            ViewBag.fak = bos;
            ViewBag.tt = tip;
            ViewBag.uni = bos;
            string result = basvuru_ilanid;
            ViewBag.ilanid = result;
           
            return View();
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Insert(tbl_basvuru p, HttpPostedFileBase file, HttpPostedFileBase file2,int tip = 0)
        {

           
            if (!ModelState.IsValid) {
                List<SelectListItem> bos = new List<SelectListItem>();
                ViewBag.uni = bos;
                ViewBag.fak = bos;
                ViewBag.bolum = bos;
              
                ViewBag.il = bos;
                ViewBag.ilce = bos;
                ViewBag.m = false;
                return View("Insert"); }



            if (ModelState.IsValid)
            {
                var response = Request["g-recaptcha-response"];
                const string secret = "6LeOE8AbAAAAAAT-hOMFm0UzTrZIMfHEzpgHKV4Z";
                //Kendi Secret keyinizle değiştirin.

                var client = new WebClient();
                var reply =
                    client.DownloadString(
                        string.Format("https://www.google.com/recaptcha/api/siteverify?secret={0}&response={1}", secret, response));

                var captchaResponse = JsonConvert.DeserializeObject<CaptchaResponse>(reply);

                if (!captchaResponse.Success) {
                    TempData["Message"] = "Lütfen güvenliği doğrulayınız.";
                    return RedirectToAction("Insert");
                }
                else
                    TempData["Message"] = "Güvenlik başarıyla doğrulanmıştır.";


                List<SelectListItem> university = (from u in db.tbl_universite.ToList()
                                                   select new SelectListItem
                                                   {
                                                       Text = u.name,
                                                       Value = u.universite_id.ToString()


                                                   }).ToList();



                List<SelectListItem> fakulte = (from u in db.tbl_fakulte.ToList()
                                                select new SelectListItem
                                                {
                                                    Text = u.name,
                                                    Value = u.fakulte_id.ToString()


                                                }).ToList();



                List<SelectListItem> bolum = (from u in db.tbl_bolum.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = u.name,
                                                  Value = u.bolum_id.ToString()


                                              }).ToList();
                List<SelectListItem> il = (from u in db.iller.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = u.sehir,
                                                  Value = u.id.ToString()


                                              }).ToList();
                List<SelectListItem> ilce = (from u in db.ilceler.ToList()
                                              select new SelectListItem
                                              {
                                                  Text = u.ilce,
                                                  Value = u.id.ToString()


                                              }).ToList();
                //List<SelectListItem> ilan = (from u in db.tbl_ilan.ToList()
                //                                   select new SelectListItem
                //                                   {
                //                                       Text = u.ilan_baslik,
                //                                       Value = u.ilan_id.ToString()


                //                                   }).ToList();

                ViewBag.uni = university;
                ViewBag.fak = fakulte;
                ViewBag.bolum = bolum;
                ViewBag.il = il;
                ViewBag.ilce = ilce;
                ViewBag.tt = tip;


                var ins = db.tbl_universite.Where(m => m.universite_id == p.tbl_universite.universite_id).FirstOrDefault();
                var fak = db.tbl_fakulte.Where(m => m.fakulte_id == p.tbl_fakulte.fakulte_id).FirstOrDefault();
                var bol = db.tbl_bolum.Where(m => m.bolum_id == p.tbl_bolum.bolum_id).FirstOrDefault();
                var il1 = db.iller.Where(m => m.id == p.iller.id).FirstOrDefault();
                var ilce1= db.ilceler.Where(m => m.id == p.ilceler.id).FirstOrDefault();

                p.tbl_bolum = bol;
                p.tbl_fakulte = fak;
                p.tbl_universite = ins;
                p.iller = il1;
                p.ilceler = ilce1;

                //p.basvuru_tip = tip;
                p.basvuru_basvurutarihi = DateTime.Now;

               
                p.basvuru_foto = "a.jpg";
                if (file != null)
                {
                    if (file.ContentLength > 0)
                    {
                        int MaxContentLength = 1024 * 1024 * 1; //3 MB
                        string[] AllowedFileExtensions = new string[] { ".jpg", ".jpeg" ,".gif", ".png", ".pdf" };

                        if (!AllowedFileExtensions.Contains(file.FileName.Substring(file.FileName.LastIndexOf('.'))))
                        {
                            ModelState.AddModelError("File", "Please file of type: " + string.Join(", ", AllowedFileExtensions));
                            return View();
                        }

                        else if (file.ContentLength > MaxContentLength)
                        {
                            ModelState.AddModelError("File", "Your file is too large, maximum allowed size is: " + MaxContentLength + " MB");
                            return View();
                        }
                        else 
                        {
                            var fileName = Path.GetFileName(file.FileName);
                            var path = Path.Combine(Server.MapPath("~/Uploads/Image"), fileName);
                            file.SaveAs(path);
                            p.basvuru_foto = fileName;
                            //var fileName2 = Path.GetFileName(file2.FileName);
                            //var path2 = Path.Combine(Server.MapPath("~/Uploads/Cv"), fileName2);
                            //file.SaveAs(path2);
                            //p.basvuru_cv = fileName2;


                            ViewBag.Message = "File uploaded successfully";


                        }
                        
                        
                    }
                }
                if (file2 != null)
                {
                    if (file2.ContentLength > 0)
                    {
                        int MaxContentLength2 = 1024 * 1024 * 2; //2 MB
                        string[] AllowedFileExtensions2 = new string[] { ".jpg", ".gif", ".png", ".pdf" };

                        if (!AllowedFileExtensions2.Contains(file2.FileName.Substring(file2.FileName.LastIndexOf('.'))))
                        {
                            ModelState.AddModelError("File", "Please file of type: " + string.Join(", ", AllowedFileExtensions2));
                            return View();
                        }

                        else if (file2.ContentLength > MaxContentLength2)
                        {
                            ModelState.AddModelError("File", "Your file is too large, maximum allowed size is: " + MaxContentLength2 + " MB");
                            return View();
                        }
                        else
                        {

Views/Basvuru/EmployeeDetail.cshtml
@model stajdeneme.Models.tbl_basvuru
@{
    ViewBag.Title = "EmployeeDetail";
    Layout = null;
}
<title>Yeşil-Mavi Yazılım</title>
<div class="panel panel-default">
    <div class="panel-body">

        @if (ViewBag.f == Model.basvuru_foto)
        {
            <div class="form-group col-md-12">
                <label>
                    fotograf
                </label>

                <a href="#" class="thumbnail" width="100px" height="100px">
                    <img src="@Url.Content(String.Format("~/Uploads/Image/{0}", @Model.basvuru_foto))" width="200px" height="250px" name="1" />
                </a>
            </div>

        }
        else
        {
            <div class="form-group col-md-4">

                <label>
                    MVC
                </label>
                <p>@Model.basvuru_becerilermvc</p>
            </div><div class="form-group col-md-4">
                <label>
                    ASPNET
                </label>
                <p>@Model.basvuru_becerileraspnet</p>
            </div><div class="form-group col-md-4">
                <label>
                    SQL
                </label>
                <p>@Model.basvuru_becerilersql</p>
            </div><div class="form-group col-md-4">
                <label>
                    C#
                </label>
                <p>@Model.basvuru_becerilerc_</p>
            </div><div class="form-group col-md-4">
                <label>
                    jS
                </label>
                <p>@Model.basvuru_becerilerjs</p>
            </div><div class="form-group col-md-4">
                <label>
                    JQUERY
                </label>
                <p>@Model.basvuru_becerilerjquery</p>
            </div><div class="form-group col-md-4">
                <label>
                    JAVA
                </label>
                <p>@Model.basvuru_becerilerjava</p>
            </div><div class="form-group col-md-4">
                <label>
                    CSS
                </label>
                <p>@Model.basvuru_becerilercss</p>
            </div><div class="form-group col-md-4">
                <label>
                    HTML
                </label>
                <p>@Model.basvuru_becerilerhtml</p>
            </div><div class="form-group col-md-4">
                <label>
                    XML
                </label>

                <p>@Model.basvuru_becerilerxml</p>
            </div><div class="form-group col-md-4">
                <label>
                    JSON
                </label>

                <p>@Model.basvuru_becerilerjson</p>
            </div>
            <div class="form-group col-md-4">
                <label>
                    İNGİLİZCE
                </label>

                <p>@Model.basvuru_yabancıdil</p>
            </div>

            <hr />

            <div class="form-group col-md-4">
                <label>
                    REFERANS
                </label>

                <p>@Model.basvuru_referans</p>
            </div>
            <div class="form-group col-md-4">
                <label>
                    Not Ortalama
                </label>

                <p>@Model.basvuru_notortalama</p>
            </div>
            <div class="form-group col-md-4">
                <label>
                    GİTHUB
                </label>

                <p>@Model.basvuru_github</p>
            </div>
            <div class="form-group col-md-4">
                <label>
                    SAGLIK DURUMU
                </label>

                <p>@Model.basvuru_saglık</p>
            </div>
            <div class="form-group col-md-4">
                <label>
                    COVİD DURUMU
                </label>

                <p>@Model.basvuru_covid</p>
            </div>
            <div class="form-group col-md-4">
                <label>
                    Başvuru Tarihi
                </label>

                <p>@Model.basvuru_basvurutarihi</p>
            </div>
            <div class="form-group col-md-4">
                <label>
                    Yaşadığı il
                </label>

                <p>@Model.iller.sehir</p>
            </div>
            <div class="form-group col-md-4">
                <label>
                   Yaşadığı ilçe
                </label>

                <p>@Model.ilceler.ilce</p>
            </div>
            <div class="form-group col-md-12">
                <label>
                    Açık Adres
                </label>

                <p>@Model.basvuru_adres</p>
            </div>

            <div class="form-group col-md-12">
                <label>
                    BİZİ NASIL BULDUNUZ
                </label>

                <p>@Model.basvuru_nasılbuldunuz</p>
            </div>
            <div class="form-group col-md-12">
                <label>
                    HOBİLER
                </label>

                <p>@Model.basvuru_hobiler</p>
            </div>
            <div class="form-group col-md-12">
                <label>
                    BİZİ NEDEN SEÇTİNİZ
                </label>

                <p>@Model.basvuru_bizinedensectiniz</p>
            </div>
            <div class="form-group col-md-12">
                <label>
                    EK OLARAK..
                </label>

                <p>@Model.basvuru_diger</p>
            </div>
            <div class="form-group col-md-12">
                <label>
                    ADMİN YORUM
                </label>

                <p>@Model.basvuru_adminyorum</p>
            </div>



        }

    </div>
</div>


Views/Basvuru/Guncelle2.cshtml
@model stajdeneme.Models.tbl_basvuru
@{
    ViewBag.Title = "Guncelle2";
    Layout = "~/Views/Shared/_ViewLayout.cshtml";
}
<title>Yeşil-Mavi Yazılım</title>
@using (Html.BeginForm("RGuncelle2", "Basvuru", FormMethod.Post))
{<div style="margin-top:10px">

        @Html.HiddenFor(m => m.basvuru_id, new { @class = "form-control" })
    </div>

    <div style="margin-top:10px">
        @Html.Label("İsim")
        @Html.TextBoxFor(m => m.basvuru_ad, new { @class = "form-control" })
    </div>
    <div style="margin-top:10px">
        @Html.Label("Soyisim")
        @Html.TextBoxFor(m => m.basvuru_soyad, new { @class = "form-control" })
    </div>
    <div style="margin-top:10px">
        @Html.Label("Tel")
        @Html.TextBoxFor(m => m.basvuru_tel, new { @class = "form-control" })
    </div>
    <div style="margin-top:10px">
        @Html.Label("E-mail")
        @Html.TextBoxFor(m => m.basvuru_email, new { @class = "form-control" })
    </div>
    <div style="margin-top:10px">
        @Html.Label("Yorum")
        @Html.TextAreaFor(m => m.basvuru_adminyorum, new { @class = "form-control" })
    </div>
    <div style="margin-top:10px">
        <button class="btn btn-success">Güncelle</button>
        <button data-target="~/Basvuru/Index" class="btn btn-danger">Geri</button>
    </div>

}

Views/Basvuru/Index.cshtml
@using stajdeneme.Models
@*@model List<tbl_basvuru>*@
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<tbl_basvuru>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ViewLayout.cshtml";
}
<meta name="viewport" content="width=device-width" />
<title>Yeşil-Mavi Yazılım</title>
<link href="~/Content/dist/magnific-popup.css" rel="stylesheet" />
<style>


    .mfp-close {
        cursor: pointer !important;
    }

    body {
        background: #f1f1f1;
    }

    table {
        background: #fff;
    }

    th, td {
        padding: 15px;
        text-align: left;
    }

    tr:hover {
        background-color: #f5f5f5;
    }

    .styled-table {
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        font-family: sans-serif;
        min-width: 400px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }

        .styled-table thead tr {
            background-color: #009879;
            color: #ffffff;
            text-align: left;
        }

        .styled-table th,
        .styled-table td {
            padding: 12px 15px;
        }

        .styled-table tbody tr {
            border-bottom: 1px solid #dddddd;
        }

            .styled-table tbody tr:nth-of-type(even) {
                background-color: #f3f3f3;
            }

            .styled-table tbody tr:last-of-type {
                border-bottom: 2px solid #009879;
            }
</style>
<script src="~/Scripts/jquery-2.1.4.min.js"></script>
<script src="~/Content/dist/jquery.magnific-popup.min.js"></script>


@using (@Html.BeginForm("Index", "Basvuru", FormMethod.Get))
{
    <p>
        <h3>Arama...</h3>@Html.TextBox("ara", null, new { @autocomplete = "off", @placeholder = "Arama.." })

        <button class="btn btn-primary btn-sm" type="submit" value="Ara"> <i class="glyphicon glyphicon-search"></i></button>
        @*<a href="@Url.Action("ExcelExport", "Basvuru")" class="btn btn-success btn-sm"> Excel Export  <i class="glyphicon glyphicon-download-alt"> </i></a>*@
        <a href="#" class="btn btn-success btn-sm" id="export">Excele Aktar  <i class="glyphicon glyphicon-download-alt"> </i></a>
        <a href="~/ilan/index" class="btn btn-warning btn-sm" id="export">İlanlar  <i class="glyphicon glyphicon-arrow-right"> </i></a>
        <a href="~/Login/Login" class="btn btn-danger btn-sm" id="export">Çıkış  <i class="glyphicon glyphicon glyphicon-off"> </i></a>
        <br />
    </p>
}
<br />
<table class="table table-bordered styled-table">
    <tr>
        <th>Sıra No</th>
        <th>Başvuru Tarihi</th>
        <th> Foto</th>
        <th> Adı</th>
        <th> Soyad</th>
        <th> Başvuru Tipi</th>
        <th> Pozisyon</th>
        <th> Uyruk</th>
        <th> Tel</th>
        <th> email</th>
        <th> Okul</th>
        <th> Fakulte</th>
        <th> Bölüm</th>
        <th> Sınıf</th>
        <th>
            Başlangıç  <br />
            Bitiş tarihi
        </th>

        <th> Seçenekler</th>





    </tr>
    @{int i = 0; }
    <tbody>

        @foreach (var s in Model.OrderByDescending(s => s.basvuru_basvurutarihi))
        {



            <tr>
                <td>
                    <div>
                        @{
                            i++;
                        }
                    </div>
                    @i
                </td>
                <td>@s.basvuru_basvurutarihi </td>
                <td>
                    <div>
                        <div class="popup-gallery">
                            @*<a href="@Url.Content(String.Format("~/Uploads/Image/{0}", @s.basvuru_foto))" width="400" height="400" title="Demo1">*@

                            <a href="#" class="view dropdown-item btn btn-light" data-target="/Basvuru/EmployeeDetail?id=@s.basvuru_id&foto=@s.basvuru_foto">
                                <img src="@Url.Content(String.Format("~/Uploads/Image/{0}", @s.basvuru_foto))" width="100" height="100" />
                            </a><br />
                        </div>
                    </div>



                    @*<a href="#" class="thumbnail" width="100px" height="100px">
                                <img src="@Url.Content(String.Format("~/Uploads/Image/{0}", @s.basvuru_foto))"  name="1" />
                            </a>
                        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                    </div>
                                    <div class="modal-body">

                                                    <img src="@Url.Content(String.Format("~/Uploads/Image/{0}", @s.basvuru_foto))" style="height:400px;width: 566px;" name="1" class="img-responsive">
                                                </div>


                                             Controls

                                    </div>
                                </div>
                            </div>*@



                </td>


                <td>@s.basvuru_ad</td>
                <td>@s.basvuru_soyad</td>
                <td>@s.tbl_ilan.tbl_tip.tip_name</td>
                <td>@s.tbl_ilan.ilan_baslik</td>
                <td>@s.basvuru_uyruk</td>
                <td>@s.basvuru_tel</td>
                <td>@s.basvuru_email</td>
                <td>@s.tbl_universite.name</td>
                <td>@s.tbl_fakulte.name</td>
                <td>@s.tbl_bolum.name</td>
                <td>@s.basvuru_sınıf</td>
                <td>@s.basvuru_başlangıc<hr /> @s.basvuru_bitis</td>

                <td>
                    <div class="dropdown show">
                        <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Seçenekler<i class="glyphicon glyphicon-arrow-down"> </i>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="max-width:10px">
                            <a href="#" class="view dropdown-item btn btn-light" data-target="/Basvuru/EmployeeDetail/@s.basvuru_id">Git</a><br />
                            @Html.ActionLink("İndir ", "DownloadFile", new { fileName = s.basvuru_cv }, new { @class = "dropdown-item btn btn-light" })<br />
                            <a href="/Basvuru/Sil/@s.basvuru_id" class="dropdown-item btn btn-light">Sil</a><br />
                            <a href="/Basvuru/Guncelle2/@s.basvuru_id" class="dropdown-item btn btn-light">Güncelle</a>
                        </div>
                    </div>

                </td>
                @*<td><a href="#" class="view btn btn-danger" data-target="/Basvuru/EmployeeDetail/@s.basvuru_id">Git</a></td>
                    <td>@Html.ActionLink("İndir ", "DownloadFile", new { fileName = s.basvuru_cv }, new { @class = "btn btn-primary" })</td>

                    <td><a href="/Basvuru/Guncelle2/@s.basvuru_id" class="btn btn-success">Güncelle</a></td>*@
            </tr>

        }
    </tbody>
</table>
<div class="modal fade" id="modelView" tabindex="-1" role="dialog" aria-labelledby="">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"> Details</h4>
            </div>
            <form method="post">
                <div class="modal-body">
                    @*görünücek kısım*@


                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" type="button" data-dismiss="modal">Kapat  </button>

                </div>
            </form>
        </div>
    </div>
</div>
@Html.PagedListPager((IPagedList)Model, sayfa => Url.Action("Index", new { sayfa }))


<script>
    $(function () {
        // a tagimizde bulunan .view classımıza click olduğunda
        $("body").on("click", ".view", function () {
            //data-target dan url mizi al
            var url = $(this).data("target");
            //bu urlimizi post et
            $.post(url, function (data) { })
                //eğer işlemimiz başarılı bir şekilde gerçekleşirse
                .done(function (data) {
                    //gelen datayı .modal-body mizin içerise html olarak ekle
                    $("#modelView .modal-body").html(data);
                    //sonra da modalimizi göster
                    $("#modelView").modal("show");
                })
                //eğer işlem başarısız olursa
                .fail(function () {
                    //modalımızın bodysine Error! yaz
                    $("#modelView .modal-body").text("Error!!");
                    //sonra da modalimizi göster
                    $("#modelView").modal("show");
                })

        });
    })</script>

<script>
    $(function () {
        $('.popup-gallery').magnificPopup({
            delegate: 'a',
            type: 'image',
            tLoading: 'Loading image #%curr%...',
            mainClass: 'mfp-img-mobile',
            cursor: 'mfp-zoom-out-cur',
            preloader: false,
            gallery: {
                enabled: true,
                navigateByImgClick: true,
                preload: [0, 1] // Will preload 0 - before current, and 1 after the current image
            },
            image: {
                tError: '<a href="%url%">The image #%curr%</a> could not be loaded.',
                titleSrc: function (item) {
                    return item.el.attr('title') + '<br>by Gateway';
                }
            }
        });

        $('.openP').magnificPopup({
            disableOn: 700,
            type: 'iframe',
            mainClass: 'mfp-fade',
            removalDelay: 160,
            preloader: false,
            fixedContentPos: false
        });

    });
</script>
<script>
    $(function () {
        $.validator.methods.date = function (value, element) {
            return this.optional(element) || moment(value, "DD.MM.YYYY", true).isValid();
        }
    });</script>
<script>
    $(document).ready(function () {
        $("#export").click(function () {
            ExportToExcel();
        });
    });

    function ExportToExcel()
    {
        var url = '@Url.Action("GridExportToExcel", "Basvuru")';
        window.open(url);
    }
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.thumbnail').click(function () {
            var name = $(this).find('img').attr('src');
            var mname = $('.carousel-inner').find("img[src='" + $(this).find('img').attr('src') + "']");
            $('.carousel-innerdiv').removeClass("active");
            $(mname).parent().addClass("active");
            $('#myModal').modal({
                backdrop: 'static',
            }, 'show');
        });
        $(function () {
            $("#myCarousel").carousel({
                interval: 5000
            });
        });
    });</script>